-- 일일 업무 기록 테이블
-- 각 멤버별로 날짜당 1개의 로그 (금일/다음날 업무)
create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  log_date date not null,
  today_content text default '',
  tomorrow_content text default '',
  tagged_project_ids bigint[] default '{}',
  tagged_task_ids bigint[] default '{}',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique (member_id, log_date)
);

create index if not exists daily_logs_log_date_idx on public.daily_logs (log_date);
create index if not exists daily_logs_member_id_idx on public.daily_logs (member_id);

-- RLS 열기 (프로젝트가 anon key로 직접 접근하므로)
alter table public.daily_logs enable row level security;

drop policy if exists "daily_logs read" on public.daily_logs;
create policy "daily_logs read" on public.daily_logs for select using (true);

drop policy if exists "daily_logs write" on public.daily_logs;
create policy "daily_logs write" on public.daily_logs for all using (true) with check (true);
