-- 이슈 코멘트 (스레드)
create table if not exists public.issue_comments (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.issues(id) on delete cascade,
  author_id bigint references public.members(id) on delete set null,
  content text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists issue_comments_issue_id_idx on public.issue_comments (issue_id);
create index if not exists issue_comments_created_at_idx on public.issue_comments (created_at);

alter table public.issue_comments enable row level security;

drop policy if exists "issue_comments read" on public.issue_comments;
create policy "issue_comments read" on public.issue_comments for select using (true);

drop policy if exists "issue_comments write" on public.issue_comments;
create policy "issue_comments write" on public.issue_comments for all using (true) with check (true);
