-- 프로젝트 단계별 산출물 체크리스트
create table if not exists public.project_artifacts (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  phase text not null,              -- 'planning' | 'design' | 'development' | 'test'
  type text not null,               -- 'meeting_notes' | 'ia' | 'swimlane' | 'ux_proto' | 'ui_design' | 'screen_spec' | 'api_spec' | 'qa_checklist' | 'custom'
  title text not null,
  url text default '',
  status text default 'not_started',-- 'not_started' | 'draft' | 'reviewing' | 'done'
  note text default '',
  sort_order int default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists project_artifacts_project_id_idx on public.project_artifacts (project_id);
create index if not exists project_artifacts_phase_idx on public.project_artifacts (phase);

alter table public.project_artifacts enable row level security;

drop policy if exists "project_artifacts read" on public.project_artifacts;
create policy "project_artifacts read" on public.project_artifacts for select using (true);

drop policy if exists "project_artifacts write" on public.project_artifacts;
create policy "project_artifacts write" on public.project_artifacts for all using (true) with check (true);
