-- Create projects table
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  group_name TEXT NOT NULL,
  task TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Development', 'Review', 'Launch')),
  area TEXT NOT NULL,
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100)
);

-- Insert initial data
INSERT INTO projects (title, group_name, task, status, area, progress)
VALUES 
  ('SK 텔링크 (크루페이)', '크루페이', '백엔드 연동 및 검수 수정', 'Review', 'Full-stack', 85),
  ('서울대학교 2차', 'SNU', '프론트엔드 작업 (관리자/메인)', 'Development', 'Frontend', 60),
  ('비디치과', '비디치과', '2차 검수 및 수정 진행 중', 'Review', 'Frontend', 92),
  ('스카이써니', '스카이써니', '최종 검수 보완 및 출시 진행', 'Launch', 'Full-stack', 98),
  ('리모메드', '리모메드', 'PC/태블릿 앱 프론트 개발', 'Development', 'Frontend', 45),
  ('프라코', '프라코', '관리자 프론트 API 연동', 'Development', 'Admin', 30),
  ('리모코리아', '리모코리아', 'PG 교체 및 2차 검수 수정', 'Review', 'Backend', 88),
  ('온투인', '온투인', '앱 프론트엔드 및 백엔드', 'Development', 'Full-stack', 55),
  ('온플레이어', '온플레이어', '운영 출시 대기 중', 'Launch', 'Frontend', 95),
  ('웨이브오더', '웨이브오더', '정산 이슈 확인 및 처리', 'Development', 'Backend', 70);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all users to read (for demo purposes)
CREATE POLICY "Allow public read access" ON projects FOR SELECT USING (true);

-- Create policy to allow all users to update (for demo purposes)
CREATE POLICY "Allow public update access" ON projects FOR UPDATE USING (true);
